title: From Bytes To Programs
description: Learn programming from the machine up with FASM.
url: https://kroq86.github.io
baseurl: /fasm-handbook
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
kramdown:
  input: GFM
header_pages:
  - book/index.md
  - fasm-mac.md
  - examples.md
  - reference-guide-full.md
defaults:
  - scope:
      path: ""
    values:
      layout: page
